server: 
  port: 3344 
  
spring:
  application:
    name:  springcloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:liwanghonggc/SpringCloudConfig.git          #GitHub上面的git仓库名字,配置以后可以使用URL访问: http://config3344.com:3344/application-test.yml
 

