server: 
  port: 9527
 
spring: 
  application:
    name: springcloud-zuul
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


zuul:                                                                             #配置以后可以使用URL访问微服务:http://zuul.com:9527/springcloud-dept/dept/get/1
  routes:                                                                         #上面使用URL访问中,有暴露微服务的具体名字
    mydept.serviceId: springcloud-dept                                            #可以配置路由屏蔽掉具体的微服务名称,使用URL访问:http://zuul.com:9527/mydept/dept/get/1
    mydept.path: /mydept/**
  ignored-services: springcloud-dept                                              #配置禁止使用原URL访问,可以使用"*"配置
  prefix: /lwh                                                                    #配置访问前缀